### PR TITLE
Update configuration.md

### PR DESCRIPTION
**Pull request by Rajitha20H**

### CODE REVIEW

**Comment by Rajitha20H** [comment]
@Fryguy, can you please merge this PR as per last comment in https://github.ibm.com/katamari/dev-issue-tracking/issues/24394#issuecomment-42873502.

**Comment by rwellon** [comment]
@miq-bot add-label nadorf/yes?

**Comment by rwellon** [comment]
@miq-bot add-label najdorf/yes?

**Comment by Fryguy** [comment]
I'll fix this one.

**Comment by Fryguy** [comment]
Manual backport to `najdorf`:

```
commit 593648f66b73fcd9ed2088e79b63af76f08a9bdf (HEAD -> najdorf, upstream/najdorf)
Author: Jason Frey <fryguy9@gmail.com>
Date:   Tue Apr 19 08:09:18 2022 -0400

    Merge pull request #1660 from Rajitha20H/origin/RSP_internal-database

    Update configuration.md

    (cherry picked from commit f4ce8d6cb75daf5d92379c083b7181848306c388)
```

**Pull request merged**
