### PR TITLE
Delete deprecated authentication and API docs

### PR DESCRIPTION
**Pull request by dehawkins512**
rest_api folder is no longer used for api docs.
The current api docs are in the api folder.
managing_authentication folder is no longer used for authentication docs.
The current authentication docs are in the auth folder.

### CODE REVIEW

**Comment by dehawkins512** [comment]
@miq-bot assign @Fryguy

**Comment by jvlcek** [comment]
👍

**Comment by bdunne** [comment]
@dehawkins512 Is this still WIP?

**Comment by dehawkins512** [comment]
> 
> 
> @dehawkins512 Is this still WIP?

@bdunne Removing the WIP, this one can be merged now.

**Pull request merged**
