### PR TITLE
Update automation_providers.md

### PR DESCRIPTION
**Pull request by rwellon**
Pull request for updated capabilities matrix page for embedded workflows.

### CODE REVIEW

**Comment by rwellon** [comment]
@miq-bot assign @agrare

**Comment by rwellon** [comment]
@miq-bot assign @Fryguy

**Comment by rwellon** [comment]
@miq-bot add_labels petrosian/yes?, quinteros/yes?

**Review by agrare — APPROVED** [review]
LGTM

**Comment by Fryguy** [comment]
Backported to `quinteros` in commit 62e16184bf3a20363122aaec4746c274e8adbf75.

```text
commit 62e16184bf3a20363122aaec4746c274e8adbf75
Author: Adam Grare <adam@grare.com>
Date:   Tue Oct 10 12:44:40 2023 -0400

    Merge pull request #1750 from rwellon/RW-IAE-capabilities
    
    Update automation_providers.md
    
    (cherry picked from commit 743abed387c0c9a07766846f24b95228fc33d09b)
```

**Pull request merged**
