### PR TITLE
Fix the backup label selector

### PR DESCRIPTION
**Pull request by bdunne**

### CODE REVIEW

**Review by Fryguy — APPROVED** [review]

**Comment by Fryguy** [comment]
Should this go to kasparov too?

**Comment by bdunne** [comment]
Yes, since https://github.com/ManageIQ/manageiq-documentation/pull/1526 went to kasparov

**Comment by Fryguy** [comment]
Backported to `lasker` in commit e6704bb0c7ebb94a3d817e73f5ab1fadaaafba48.

```text
commit e6704bb0c7ebb94a3d817e73f5ab1fadaaafba48
Author: Jason Frey <fryguy9@gmail.com>
Date:   Wed Feb 24 10:57:38 2021 -0500

    Merge pull request #1533 from bdunne/correct_backup_label
    
    Fix the backup label selector
    
    (cherry picked from commit ba796c5cb646371190a6e75d15a1f292c6331d9e)
```

**Comment by Fryguy** [comment]
Backported to `kasparov` in commit 12b56dae31a4cf755e9aa4fc1a9ef27ac13bf1fe.

```text
commit 12b56dae31a4cf755e9aa4fc1a9ef27ac13bf1fe
Author: Jason Frey <fryguy9@gmail.com>
Date:   Wed Feb 24 10:57:38 2021 -0500

    Merge pull request #1533 from bdunne/correct_backup_label
    
    Fix the backup label selector
    
    (cherry picked from commit ba796c5cb646371190a6e75d15a1f292c6331d9e)
```

**Pull request merged**
