### PR TITLE
Remove v2v documentation

### PR DESCRIPTION
**Pull request by jrafanie**
This was removed as part of https://github.com/ManageIQ/manageiq-api/pull/1085
and the large project to remove v2v:
https://github.com/ManageIQ/manageiq/issues/21379

This was removed on master and najdorf but still remains on morphy.  I don't know if we maintain old documentation here but opened this to discuss it.

### CODE REVIEW

**Comment by Fryguy** [comment]
>  I don't know if we maintain old documentation here but opened this to discuss it.

We have branches for the old code, so we can delete on master and also backport to najdorf.

**Comment by Fryguy** [comment]
@jrafanie Be sure to also remove from the left side menu, which is, annoyingly, here: https://github.com/ManageIQ/manageiq.org/blob/master/site/_data/menus/api_menu.yml

**Comment by jrafanie** [comment]
> @jrafanie Be sure to also remove from the left side menu, which is, annoyingly, here: [https://github.com/ManageIQ/manageiq.org/blob/master/site/_data/menus/api_menu.yml](https://github.com/ManageIQ/manageiq.org/blob/master/site/_data/menus/api_menu.yml?rgh-link-date=2022-06-27T15%3A09%3A08Z)

Will do.

**Comment by Fryguy** [comment]
> I don't know why it's here and there

🤷  https://github.com/ManageIQ/manageiq.org/issues/814

**Comment by Rajitha20H** [comment]
@jrafanie @Fryguy , Do these changes apply to MCM as well? Because since we removed the files, the reference to these files in summary.md in MCM is holding up the build. If they are not needed in MCM, we can remove the references.

**Comment by jrafanie** [comment]
> @jrafanie @Fryguy , Do these changes apply to MCM as well?

2.3 IM no.  https://github.com/ManageIQ/manageiq-api/pull/1085 wasn't in morphy.
3.4 IA yes.  It was in najdorf.

**Comment by Fryguy** [comment]
Backported to `najdorf` in commit 70d540ae02b220cbfd35894161721844d60bd559.

```text
commit 70d540ae02b220cbfd35894161721844d60bd559
Author: Jason Frey <fryguy9@gmail.com>
Date:   Mon Jun 27 13:11:32 2022 -0400

    Merge pull request #1681 from jrafanie/remove_v2v_documentation
    
    Remove v2v documentation
    
    (cherry picked from commit 1461fe7717d4fd44c27e84f25f01bd960bb2b7e3)
```

**Pull request merged**
