### PR TITLE
Update Capabilities Matrix Service Catalog

### PR DESCRIPTION
**Pull request by agrare**
VPC, HMC, and KubeVirt/OSV all have Service Catalog support

* https://github.com/ManageIQ/manageiq-providers-ibm_cloud/pull/362
* https://github.com/ManageIQ/manageiq-providers-ibm_power_hmc/pull/137
* https://github.com/ManageIQ/manageiq-providers-kubevirt/pull/250

### CODE REVIEW

**Review by Fryguy — APPROVED** [review]

**Comment by Fryguy** [comment]
@agrare Do you know when this support was added?  We can backport that far back.

**Comment by agrare** [comment]
> Do you know when this support was added? We can backport that far back.

I linked the three different PRs, they were merged over a long period of time so if we want to backport it'll have to be with direct PRs

**Comment by Fryguy** [comment]
Ok, so at a minimum this PR can go back to radjabov

**Comment by Fryguy** [comment]
Backported to `radjabov` in commit 8edf9ba6880eeaf1594fa39855315d858c2803b4.

```text
commit 8edf9ba6880eeaf1594fa39855315d858c2803b4
Author: Jason Frey <fryguy9@gmail.com>
Date:   Thu Dec 5 09:49:50 2024 -0500

    Merge pull request #1824 from agrare/update_service_catalog_support
    
    Update Capabilities Matrix Service Catalog
    
    (cherry picked from commit 013d29f72a7f7c93090218aa917a8ae7568ed7c1)
```

**Pull request merged**
