### PR TITLE
Kubevirt/OSV Capabilities Update

### PR DESCRIPTION
**Pull request by nasark**
We now support metrics and vm event timelines for Kubevirt and OSV providers

@miq-bot assign @agrare 
@miq-bot add_label enhancement
@miq-bot add_reviewer @qahmed1998, @agrare, @Fryguy

### CODE REVIEW

**Review by agrare — APPROVED** [review]
We should evaluate if some of the other features like `Chargeback by Allocation/Utilization` / `Alerts` are enabled by Events+Metrics but this is a great start.

**Comment by qahmed1998** [comment]
Thanks for adding the doc update.

**Comment by qahmed1998** [comment]
Does this need to be back-ported to `radjabov`?
FYI @Fryguy

**Comment by Fryguy** [comment]
Backported to `radjabov` in commit ba25f4caa094ea097fc0da64740ae8ba36a28dc3.

```text
commit ba25f4caa094ea097fc0da64740ae8ba36a28dc3
Author: Adam Grare <adam@grare.com>
Date:   Wed Dec 11 16:04:37 2024 -0500

    Merge pull request #1825 from nasark/kubevirt_osv_metrics_events
    
    Kubevirt/OSV Capabilities Update
    
    (cherry picked from commit 63f497e3d85e007c02bee3fcb03ff796dceab7fb)
```

**Pull request merged**
