### PR TITLE
Update fulfilling_requests.md

### PR DESCRIPTION
**Pull request by meghasalunke1**
Updated the step

### CODE REVIEW

**Comment by meghasalunke1** [comment]
@miq-bot assign @Fryguy

**Comment by meghasalunke1** [comment]
@miq-bot add_label bug

**Comment by meghasalunke1** [comment]
@miq-bot add-label oparin/yes

**Comment by rwellon** [comment]
@Fryguy This change did not go into oparin - is the backport still pending?

**Comment by Fryguy** [comment]
Backported to `oparin` in commit 736ebba5831b017e0b87648604c82cb18c6da983.

```text
commit 736ebba5831b017e0b87648604c82cb18c6da983
Author: Jason Frey <fryguy9@gmail.com>
Date:   Tue Oct 18 09:51:55 2022 -0400

    Merge pull request #1697 from meghasalunke1/MS_35481
    
    Update fulfilling_requests.md
    
    (cherry picked from commit d2a4793899e9aa3e3c0b4476873904bcc4c0afc1)
```

**Pull request merged**
