### PR TITLE
Remove incorrect note about disabled providers

### PR DESCRIPTION
**Pull request by Fryguy**
@agrare Please review.

~~Alternatively, should we remove this section or reword it?  It's meant for downstream cases where the permissions file is present, but we don't have one upstream.~~ EDIT: Removing the section entirely, because it's wrong...see discussion

### CODE REVIEW

**Comment by agrare** [comment]
Yeah if this isn't an issue upstream seems like it should be removed and only exist in the downstream docs cc @dehawkins512

**Comment by Fryguy** [comment]
We really should have _something_ in the upstream docs for the permissions file, but perhaps not make it AWS specific?

**Comment by agrare** [comment]
> We really should have something in the upstream docs for the permissions file, but perhaps not make it AWS specific?

Maybe?  We don't have a permissions.yml upstream at all though right?

**Comment by Fryguy** [comment]
Right, but if a user creates a permissions.yml for their installation, it will be honored.

**Comment by Fryguy** [comment]
It's kind of weird, because it's specifically meant for downstream distributions that don't even want to allow enabling via settings.  It's like an uber-disable.

**Comment by agrare** [comment]
> Right, but if a user creates a permissions.yml for their installation, it will be honored.

Yeah good point, definitely not AWS specific but maybe in the top-level "Managing Providers" overview?

**Comment by Fryguy** [comment]
> Yeah good point, definitely not AWS specific but maybe in the top-level "Managing Providers" overview?

Yeah that's probably a good place.  Generically, any provider could be added to the permissions file to prevent it from even being honored.

Actually now that I wrote that, this line is completely wrong (or maybe I'm misinterpreting it?)  The permissions.yml prevents the _provider_ from showing up, not specific regions.  Specific regions are handled with the normal Advanced Settings.

**Comment by agrare** [comment]
I think this must have been from when this was a whitelist not a blacklist?

Actually wait, regions aren't in permissions.yml only top-level providers are

**Comment by Fryguy** [comment]
Ok, so here's what I think we should do.  We should still add a section to Managing Providers about permissions.yml.  Separately, we should just remove this line entirely...I'll update this PR to do the latter.

**Comment by Fryguy** [comment]
Ok, updated with a complete removal.

**Review by agrare — APPROVED** [review]

**Pull request merged**
