### PR TITLE
Update configuration.md

### PR DESCRIPTION
**Pull request by qahmed1998**

### CODE REVIEW

**Comment by qahmed1998** [comment]
@miq-bot add_labels radjabov/yes?

**Comment by qahmed1998** [comment]
@miq-bot assign @Fryguy

**Comment by qahmed1998** [comment]
@miq-bot assign @kbrock

**Comment by Fryguy** [comment]
Backported to `radjabov` in commit 96b8dc16585a5ca29b5b5a072cad5d113e5ac75d.

```text
commit 96b8dc16585a5ca29b5b5a072cad5d113e5ac75d
Author: Keenan Brock <keenan@thebrocks.net>
Date:   Tue Apr 9 12:28:39 2024 -0400

    Merge pull request #1788 from qahmed1998/QA-add-integration
    
    Update configuration.md
    
    (cherry picked from commit a51a2fde7898017bc639669d86f0976b9addb529)
```

**Pull request merged**
