### PR TITLE
Updated topics

### PR DESCRIPTION
**Pull request by meghasalunke1**
- Updated Adding a Playbook Repository steps
- Changed Adding credentials
- Moved vault credential type as a bullet
- Updated steps for Adding Tags to Ansible Playbooks", "Adding Tags to Ansible Repositories", "Adding Tags to Ansible Credentials topics

### CODE REVIEW

**Comment by meghasalunke1** [comment]
@miq-bot assign @Fryguy,

**Comment by meghasalunke1** [comment]
@miq-bot add_label bug

**Comment by meghasalunke1** [comment]
@miq-bot add-label oparin/yes?

**Comment by meghasalunke1** [comment]
@miq-bot assign @Fryguy

**Review by Fryguy — APPROVED** [review]

**Comment by Fryguy** [comment]
Backported to `oparin` in commit 3e8517a202d6c1f8373dc54b8de1717bf4f3ba5e.

```text
commit 3e8517a202d6c1f8373dc54b8de1717bf4f3ba5e
Author: Jason Frey <fryguy9@gmail.com>
Date:   Mon Oct 17 10:08:45 2022 -0400

    Merge pull request #1694 from meghasalunke1/MS_1710
    
    Updated topics
    
    (cherry picked from commit 9a7c4519db644b453e1fc9d52fd45f37780ac942)
```

**Pull request merged**
