### PR TITLE
Added log table request information

### PR DESCRIPTION
**Pull request by meghasalunke1**
Added log table request information and note

### CODE REVIEW

**Comment by meghasalunke1** [comment]
@miq-bot assign @Fryguy

**Comment by meghasalunke1** [comment]
@miq-bot add_label bug

**Comment by meghasalunke1** [comment]
@miq-bot add-label petrosian/yes?

**Comment by meghasalunke1** [comment]
@Fryguy I believe Petrosian is for latest release.

**Comment by Fryguy** [comment]
Backported to `petrosian` in commit ca4426e880d851dfb82ecf1b2219bb2a93fbff48.

```text
commit ca4426e880d851dfb82ecf1b2219bb2a93fbff48
Author: Jason Frey <fryguy9@gmail.com>
Date:   Thu Apr 6 09:52:05 2023 -0400

    Merge pull request #1726 from meghasalunke1/MS_39769
    
    Added log table request information
    
    (cherry picked from commit b631c612d0c765108bc01219fd859af12218eb64)
```

**Pull request merged**
