### PR TITLE
Update image_import.md

### PR DESCRIPTION
**Pull request by meghasalunke1**
Fixed the broken links

### CODE REVIEW

**Comment by meghasalunke1** [comment]
@miq-bot add_label bug

**Comment by meghasalunke1** [comment]
@miq-bot add-label oparin/yes

**Comment by meghasalunke1** [comment]
@miq-bot assign @Fryguy

**Comment by Fryguy** [comment]
Backported to `oparin` in commit 20f675b65e382a6e75f8ed1ac76084e43a6300ca.

```text
commit 20f675b65e382a6e75f8ed1ac76084e43a6300ca
Author: Jason Frey <fryguy9@gmail.com>
Date:   Tue Oct 18 09:47:48 2022 -0400

    Merge pull request #1698 from meghasalunke1/MS_BrokenLink
    
    Update image_import.md
    
    (cherry picked from commit 5a2ba4f52f0c1fecd7bdabb8ffe95ba8e043ab2b)
```

**Comment by jaywcarman** [comment]
Just built locally with/without the patch and confirm that this breaks the links. This issue originated form a downstream docs issue I reported, but I don't think there is any problem in the upstream.

**Pull request merged**
