### PR TITLE
QA Updated images.

### PR DESCRIPTION
**Pull request by qahmed1998**

### CODE REVIEW

**Comment by qahmed1998** [comment]
@miq-bot assign @Fryguy

**Comment by qahmed1998** [comment]
@miq-bot add_labels radjabov/yes?, quinteros/yes?, petrosian/yes?

**Comment by Fryguy** [comment]
Backported to `radjabov` in commit a83503e00a2c5e480ac24f0c59f9c70dae7cbf93.

```text
commit a83503e00a2c5e480ac24f0c59f9c70dae7cbf93
Author: Jason Frey <fryguy9@gmail.com>
Date:   Fri Mar 15 09:42:28 2024 -0400

    Merge pull request #1785 from qahmed1998/QA-add-new-images
    
    QA Updated images.
    
    (cherry picked from commit 80d007fa0fd2a418f57676f848e285bc22fdd249)
```

**Comment by Fryguy** [comment]
Backported to `quinteros` in commit d2365b376b7275a27f521756d93017e379acf11d.

```text
commit d2365b376b7275a27f521756d93017e379acf11d
Author: Jason Frey <fryguy9@gmail.com>
Date:   Fri Mar 15 09:42:28 2024 -0400

    Merge pull request #1785 from qahmed1998/QA-add-new-images
    
    QA Updated images.
    
    (cherry picked from commit 80d007fa0fd2a418f57676f848e285bc22fdd249)
```

**Comment by Fryguy** [comment]
Backported to `petrosian` in commit 1b85ffa8a05f3f1b2464142a27cd53333e4a084a.

```text
commit 1b85ffa8a05f3f1b2464142a27cd53333e4a084a
Author: Jason Frey <fryguy9@gmail.com>
Date:   Fri Mar 15 09:42:28 2024 -0400

    Merge pull request #1785 from qahmed1998/QA-add-new-images
    
    QA Updated images.
    
    (cherry picked from commit 80d007fa0fd2a418f57676f848e285bc22fdd249)
```

**Pull request merged**
