### PR TITLE
QA Removed SCVMM provider

### PR DESCRIPTION
**Pull request by qahmed1998**

### CODE REVIEW

**Comment by qahmed1998** [comment]
@miq-bot assign @Fryguy

**Comment by qahmed1998** [comment]
@miq-bot add_labels radjabov/yes?, quinteros/yes?, petrosian/yes?

**Comment by Fryguy** [comment]
Can you remove the actual pages as well?  Or is that planned for a separate PR?

**Comment by qahmed1998** [comment]
> Can you remove the actual pages as well? Or is that planned for a separate PR?

Sure I can remove the physical page as well.

**Comment by qahmed1998** [comment]
I have removed the files @Fryguy.

**Review by Fryguy — APPROVED** [review]

**Comment by Fryguy** [comment]
Manually backported to `radjabov` via 964d88e34e7ac83ac32b032f08b5b440c010b39e

```
commit 964d88e34e7ac83ac32b032f08b5b440c010b39e (HEAD -> radjabov, upstream/radjabov)
Author: Jason Frey <fryguy9@gmail.com>
Date:   Fri Oct 11 17:59:18 2024 -0400

    Merge pull request #1816 from qahmed1998/QA-remove-vmm-provider

    QA Removed SCVMM provider

    (cherry picked from commit c01f2423de3d99cd28dd92af2ef7f8338a6ba39e)
```

**Comment by Fryguy** [comment]
Manually backported to `quinteros` via a2326368e47b73484c84fc225979d91db79ab2b8

```
commit a2326368e47b73484c84fc225979d91db79ab2b8 (HEAD -> quinteros, upstream/quinteros)
Author: Jason Frey <fryguy9@gmail.com>
Date:   Fri Oct 11 17:59:18 2024 -0400

    Merge pull request #1816 from qahmed1998/QA-remove-vmm-provider

    QA Removed SCVMM provider

    (cherry picked from commit c01f2423de3d99cd28dd92af2ef7f8338a6ba39e)
```

**Comment by Fryguy** [comment]
Manually backported to `petrosian` via 477f97faf91b38baddacb5bbb52a557d363fc407

```
commit 477f97faf91b38baddacb5bbb52a557d363fc407 (HEAD -> petrosian, upstream/petrosian)
Author: Jason Frey <fryguy9@gmail.com>
Date:   Fri Oct 11 17:59:18 2024 -0400

    Merge pull request #1816 from qahmed1998/QA-remove-vmm-provider

    QA Removed SCVMM provider

    (cherry picked from commit c01f2423de3d99cd28dd92af2ef7f8338a6ba39e)
```

**Pull request merged**
